/// Identifies a selected remote session by host and session name
struct RemoteSessionSelection: Equatable, Hashable {
    let hostId: String
    let hostName: String
    let sessionName: String

    /// Returns the auto-resize key for the active pane in a given window
    func resizeKey(paneId: String) -> String {
        "remote-\(hostId)-\(paneId)"
    }

    /// Extracts the paneId from a resizeKey generated by this type.
    static func paneId(from resizeKey: String, hostId: String) -> String {
        let prefix = "remote-\(hostId)-"
        guard resizeKey.hasPrefix(prefix) else { return resizeKey }
        return String(resizeKey.dropFirst(prefix.count))
    }
}
